/**
 * Real review queue — the heiDATA letterpress page (jagannatha1955_p03),
 * produced by the pipeline for the README figure and the launch video.
 * Generated by webapp/tools/export_queue_sample.py from the run's own JSON;
 * every value is verbatim.
 */
import type { QueueItem } from "./types";

export const LETTERPRESS_QUEUE: QueueItem[] = [
  {"text": "(४)", "alt_text": "(8)", "flags": ["digit_uncertain", "digit_conflict"], "conf": 86.16, "risk": 7.0, "bbox": [666, 289, 903, 399]},
  {"text": "(4)", "alt_text": "(४)", "flags": ["digit_uncertain", "digit_conflict"], "conf": 72.15, "risk": 7.0, "bbox": [671, 1268, 912, 1377]},
  {"text": "(५)", "alt_text": "()", "flags": ["digit_uncertain", "digit_conflict"], "conf": 82.53, "risk": 7.0, "bbox": [703, 1785, 904, 1875]},
  {"text": "gefordert durch die", "alt_text": null, "flags": ["script_mismatch"], "conf": 96.34, "risk": 2.5, "bbox": [1359, 2397, 1502, 2425]},
  {"text": "http://digi.ub.uni-heidelberg.de/diglit/jagannatha1955/0011", "alt_text": null, "flags": ["script_mismatch"], "conf": 98.71, "risk": 2.5, "bbox": [355, 2410, 1161, 2452]},
  {"text": "UNIVERSITATS-", "alt_text": null, "flags": ["script_mismatch"], "conf": 99.59, "risk": 2.5, "bbox": [17, 2414, 152, 2443]},
  {"text": "DFG", "alt_text": null, "flags": ["script_mismatch"], "conf": 97.21, "risk": 2.5, "bbox": [1357, 2419, 1518, 2487]},
  {"text": "BIBLIOTHEK", "alt_text": null, "flags": ["script_mismatch"], "conf": 99.21, "risk": 2.5, "bbox": [17, 2436, 129, 2462]},
  {"text": "© Universitatsbibliothek Heidelberg", "alt_text": null, "flags": ["script_mismatch"], "conf": 97.26, "risk": 2.5, "bbox": [620, 2455, 923, 2487]},
  {"text": "HEIDELBERG", "alt_text": null, "flags": ["script_mismatch"], "conf": 99.9, "risk": 2.5, "bbox": [16, 2457, 132, 2483]},
  {"text": "मया सर्वेबवज़्ासरएिमथ नीताः सुरगयाः।", "alt_text": null, "flags": ["invalid_sequence"], "conf": 86.13, "risk": 1.0, "bbox": [117, 492, 1343, 611]},
  {"text": "मे, पा श्रवलम्ब तुम्हारा ्रहंकार चित में लीना।", "alt_text": null, "flags": ["invalid_sequence"], "conf": 84.71, "risk": 1.0, "bbox": [203, 888, 1361, 995]},
  {"text": "्पि प्राउ्यं राज्यं तृसमिव परित्यज्य सहसा", "alt_text": null, "flags": ["invalid_sequence"], "conf": 94.48, "risk": 1.0, "bbox": [137, 1370, 1387, 1485]},
  {"text": "केषामिहपुर: ॥", "alt_text": null, "flags": ["unknown_word"], "conf": 89.14, "risk": 0.5, "bbox": [894, 690, 1328, 801]},
  {"text": "सुधातः स्वादीयः सलिलमिदमातृति पिवतां", "alt_text": null, "flags": ["unknown_word"], "conf": 90.56, "risk": 0.5, "bbox": [133, 1559, 1357, 1696]},
  {"text": "निर्वागापद्वीम ॥", "alt_text": null, "flags": ["unknown_word"], "conf": 82.47, "risk": 0.5, "bbox": [886, 1667, 1377, 1771]},
  {"text": "जनानामानन्द: परिहसति", "alt_text": null, "flags": ["unknown_word"], "conf": 95.32, "risk": 0.5, "bbox": [136, 1670, 879, 1780]},
]

export const LETTERPRESS_META = {
  source: "heidata · doi:10.11588/data/EGOKEI · cc by 4.0",
  page: "jagannatha1955_p03 · 1955 letterpress",
  tokens: 30,
  flagged: 17,
};
