"""
test_demo_asset.py — the README before/after figure must exist and be usable.

The figure is generated by `scripts/make_demo_image.py` (real pipeline output);
this guards against it being deleted or replaced by a thumbnail. Regeneration
itself is not exercised here (it runs OCR), but the generator must import.
"""
from __future__ import annotations

import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, "scripts"))

FIGURE = os.path.join(BASE_DIR, "docs", "assets", "before_after.png")


def test_before_after_figure_exists_and_is_readable():
    assert os.path.exists(FIGURE), "README figure is missing"
    assert os.path.getsize(FIGURE) > 100_000, "figure looks like a thumbnail"
    import cv2

    img = cv2.imread(FIGURE)
    assert img is not None
    h, w = img.shape[:2]
    assert w >= 900 and h >= 900, (w, h)


def test_readme_references_the_figure():
    readme = open(os.path.join(BASE_DIR, "README.md"), encoding="utf-8").read()
    assert "docs/assets/before_after.png" in readme
    assert "EGOKEI" in readme, "CC BY 4.0 attribution must stay in the caption"


def test_demo_generator_imports():
    import make_demo_image  # noqa: F401
