"""Export real review-queue samples into the frontend as typed data.

Reads the run JSONs produced by the brag asset pipeline and writes
frontend/src/lib/queue-sample.ts. The values are verbatim, so the landing
page's queue table is the same data the video and README show.

    python webapp/tools/export_queue_sample.py
"""
from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
WEBAPP = os.path.dirname(HERE)
REPO = os.path.dirname(WEBAPP)
SRC = os.path.join(REPO, "brag-output", "assets")
OUT = os.path.join(WEBAPP, "frontend", "src", "lib", "queue-sample.ts")

HEADER = """/**
 * Real review queue — the heiDATA letterpress page (jagannatha1955_p03),
 * produced by the pipeline for the README figure and the launch video.
 * Generated by webapp/tools/export_queue_sample.py from the run's own JSON;
 * every value is verbatim.
 */
import type { QueueItem } from "./types";

export const LETTERPRESS_QUEUE: QueueItem[] = [
"""

FOOTER = """]

export const LETTERPRESS_META = {
  source: "heidata · doi:10.11588/data/EGOKEI · cc by 4.0",
  page: "jagannatha1955_p03 · 1955 letterpress",
  tokens: %(tokens)d,
  flagged: %(flagged)d,
};
"""


def main() -> None:
    with open(os.path.join(SRC, "letterpress_flags.json"), encoding="utf-8") as f:
        data = json.load(f)
    rows = data.get("review", [])
    lines = [HEADER]
    for r in rows:
        item = {
            "text": r.get("text", ""),
            "alt_text": r.get("alt_text"),
            "flags": r.get("flags", []),
            "conf": r.get("conf"),
            "risk": r.get("risk"),
            "bbox": r.get("bbox"),
        }
        lines.append("  " + json.dumps(item, ensure_ascii=False) + ",\n")
    lines.append(FOOTER % {"tokens": data.get("n_tokens", 0), "flagged": len(rows)})
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("".join(lines))
    print(f"wrote {OUT} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
