"""
fetch_nepali_lexicon.py — build the Devanagari lexicon for `unknown_word` (W-B).

Sources (license + provenance recorded in docs/LICENSES.md):
  * tesseract-ocr/langdata `nep/nep.wordlist` (Apache-2.0), ~33k words
  * bikashpadhikari/nepali-brihat-sabdakosh-json `sabdakosh.json.gz` (MIT),
    ~122k headwords of the Nepal Academy Brihat Sabdakosh

Output (gitignored, like all of `data/`): a sorted NFC word list plus a
manifest with the sha256 of both raw sources and of the output. The lexicon is
optional at runtime; when absent, `document_ocr` emits no `unknown_word` flag.

Air-gapped builds pass local copies instead of downloading:

    python scripts/fetch_nepali_lexicon.py --wordlist nep.wordlist \
        --sabdakosh sabdakosh.json.gz

Usage:
    python scripts/fetch_nepali_lexicon.py
    python scripts/fetch_nepali_lexicon.py --out-dir data/lexicon --refresh
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import os
import shutil
import sys
import time
import urllib.request
from typing import Dict, List, Optional, Tuple

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)

from lexicon import MIN_WORD_LEN, is_deva_word, normalize_word  # noqa: E402

WORDLIST_URL = ("https://raw.githubusercontent.com/tesseract-ocr/langdata/"
                "master/nep/nep.wordlist")
SABDAKOSH_URL = ("https://raw.githubusercontent.com/bikashpadhikari/"
                 "nepali-brihat-sabdakosh-json/main/sabdakosh.json.gz")
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) VeriScript-Research/1.0 "
      "(offline lexicon build; contact: local)")
LEXICON_NAME = "nepali_lexicon_v1.txt"
MANIFEST_NAME = "nepali_lexicon_v1.manifest.json"
SOURCES = [
    {"name": "tesseract-ocr/langdata nep/nep.wordlist", "url": WORDLIST_URL,
     "license": "Apache-2.0"},
    {"name": "bikashpadhikari/nepali-brihat-sabdakosh-json sabdakosh.json.gz",
     "url": SABDAKOSH_URL, "license": "MIT"},
]
HEADER = (
    "# VeriScript Nepali lexicon v1\n"
    "# sources: tesseract-ocr/langdata nep/nep.wordlist (Apache-2.0);\n"
    "#          nepali-brihat-sabdakosh-json (MIT)\n"
    "# generated by scripts/fetch_nepali_lexicon.py - do not edit by hand;\n"
    "# see the manifest next to this file for hashes and provenance.\n"
)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def parse_wordlist(text: str) -> List[str]:
    """One word per line; tolerate count columns and `#` comments."""
    out: List[str] = []
    for line in text.splitlines():
        line = line.split(" ", 1)[0].strip()
        if not line or line.startswith("#"):
            continue
        out.append(line)
    return out


def parse_sabdakosh(raw: bytes) -> List[str]:
    """Headwords from the gzipped JSON dump (list of dicts with `word`)."""
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    data = json.loads(raw.decode("utf-8"))
    if isinstance(data, dict):
        data = (data.get("words") or data.get("entries") or data.get("data")
                or [])
    words: List[str] = []
    for item in data:
        word = item.get("word") if isinstance(item, dict) else item
        if isinstance(word, str):
            words.append(word)
    return words


def normalize_words(words: List[str]) -> Tuple[set, int]:
    """NFC, ZWJ/ZWNJ-free, Devanagari-only, >= MIN_WORD_LEN, deduplicated."""
    kept, dropped = set(), 0
    for w in words:
        n = normalize_word(w)
        if is_deva_word(n):
            kept.add(n)
        else:
            dropped += 1
    return kept, dropped


def build(wordlist_text: str, sabdakosh_raw: bytes) -> Dict:
    """Merged word list + per-source stats (pure; unit-tested offline)."""
    wl = parse_wordlist(wordlist_text)
    sk = parse_sabdakosh(sabdakosh_raw)
    wl_set, wl_drop = normalize_words(wl)
    sk_set, sk_drop = normalize_words(sk)
    merged = wl_set | sk_set
    return {
        "words": sorted(merged),
        "stats": {
            "wordlist_in": len(wl), "wordlist_kept": len(wl_set),
            "sabdakosh_in": len(sk), "sabdakosh_kept": len(sk_set),
            "overlap": len(wl_set & sk_set),
            "merged": len(merged),
            "dropped": wl_drop + sk_drop,
        },
    }


def write_lexicon(words: List[str], out_path: str) -> str:
    """Write header + sorted words (LF); returns the sha256 of the file text."""
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    text = HEADER + "".join(w + "\n" for w in words)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return sha256_bytes(text.encode("utf-8"))


def _download(url: str, dst: str, retries: int = 3) -> None:
    """Atomic download (..part -> replace) with retries; no partials left."""
    part = dst + ".part"
    last_err = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=120) as resp, \
                    open(part, "wb") as f:
                shutil.copyfileobj(resp, f, 1 << 16)
            os.replace(part, dst)
            return
        except Exception as e:  # noqa: BLE001
            last_err = e
            time.sleep(1.5 * (attempt + 1))
    try:
        os.remove(part)
    except OSError:
        pass
    raise RuntimeError(f"download failed after {retries}: {last_err}")


def fetch(out_dir: str, wordlist_path: Optional[str] = None,
          sabdakosh_path: Optional[str] = None, refresh: bool = False) -> Dict:
    """Download (or reuse local) sources, build the lexicon + manifest."""
    os.makedirs(out_dir, exist_ok=True)
    src_dir = os.path.join(out_dir, "sources")
    os.makedirs(src_dir, exist_ok=True)

    locals_ = [wordlist_path, sabdakosh_path]
    records: List[Dict] = []
    for meta, local in zip(SOURCES, locals_):
        dst = os.path.join(src_dir, os.path.basename(meta["url"]))
        if local:
            shutil.copyfile(local, dst)
        elif refresh or not os.path.exists(dst):
            _download(meta["url"], dst)
        raw = open(dst, "rb").read()
        records.append({**meta, "file": os.path.relpath(dst, out_dir),
                        "bytes": len(raw), "sha256": sha256_bytes(raw)})

    with open(os.path.join(out_dir, records[0]["file"]), encoding="utf-8",
              errors="replace") as f:
        wordlist_text = f.read()
    with open(os.path.join(out_dir, records[1]["file"]), "rb") as f:
        sabdakosh_raw = f.read()

    result = build(wordlist_text, sabdakosh_raw)
    lex_path = os.path.join(out_dir, LEXICON_NAME)
    out_sha = write_lexicon(result["words"], lex_path)
    manifest = {
        "kind": "nepali_lexicon",
        "version": 1,
        "name": "nepali_lexicon_v1",
        "created": time.strftime("%Y-%m-%d %H:%M:%S"),
        "filters": {
            "nfc": True, "zwj_zwnj_removed": True, "devanagari_only": True,
            "min_word_len": MIN_WORD_LEN, "deduplicated": True,
        },
        "sources": records,
        "stats": result["stats"],
        "output": {
            "file": LEXICON_NAME,
            "bytes": os.path.getsize(lex_path),
            "sha256": out_sha,
            "words": len(result["words"]),
        },
    }
    manifest_path = os.path.join(out_dir, MANIFEST_NAME)
    with open(manifest_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
        f.write("\n")
    return manifest


def main():
    ap = argparse.ArgumentParser(
        description="Build the Devanagari lexicon for the unknown_word flag")
    ap.add_argument("--out-dir", default=os.path.join(BASE_DIR, "data",
                                                      "lexicon"))
    ap.add_argument("--wordlist", default=None,
                    help="local nep.wordlist copy (air-gapped builds)")
    ap.add_argument("--sabdakosh", default=None,
                    help="local sabdakosh.json.gz copy (air-gapped builds)")
    ap.add_argument("--refresh", action="store_true",
                    help="re-download cached sources instead of reusing them")
    args = ap.parse_args()
    manifest = fetch(args.out_dir, args.wordlist, args.sabdakosh, args.refresh)
    s, out = manifest["stats"], manifest["output"]
    print(f"[lexicon] wordlist {s['wordlist_kept']}/{s['wordlist_in']} kept, "
          f"sabdakosh {s['sabdakosh_kept']}/{s['sabdakosh_in']} kept, "
          f"overlap {s['overlap']}")
    print(f"[lexicon] merged {out['words']} words -> "
          f"{os.path.join(args.out_dir, out['file'])}")
    print(f"[lexicon] sha256 {out['sha256']}")


if __name__ == "__main__":
    main()
